version: '3.4'

services:
  blazorapp:
    image: opusclassical-dotnet-image
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:8080"
      - "443:443"
    env_file:
      - OpusClassical/.env